/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolsystem.View;

/**
 *
 * @author ff
 */
public class Add_Student extends javax.swing.JFrame {

    /**
     * Creates new form Add_Student
     */
    private javax.swing.JFrame before_frame;
    private javax.swing.JFrame after_frame;
    public Add_Student() {
        initComponents();
        this.std_gender.addItem("ذكر");
        this.std_gender.addItem("أنثى");
        this.std_religion.addItem("مسلم");
        this.std_religion.addItem("مسيحى");
    }
    public void set_before_frame(javax.swing.JFrame frame){
        this.before_frame=frame;
        this.before_frame.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Std_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        std_gender = new javax.swing.JComboBox<>();
        std_brith_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        std_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        std_nat_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        std_code = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        std_address = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        std_religion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الاسم");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 150, -1));

        Std_name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(Std_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 187, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("الجنس");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 150, -1));

        std_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_genderActionPerformed(evt);
            }
        });
        getContentPane().add(std_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 187, -1));

        std_brith_date.setDateFormatString("yyyy-m-d");
        getContentPane().add(std_brith_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 187, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("تاريخ الميلاد");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 145, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("رقم الهاتف");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 145, -1));

        std_phone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(std_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 187, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("الرقم القومى");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 140, -1));

        std_nat_id.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(std_nat_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 187, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("الدين");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 140, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("كود الطالب");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 145, -1));

        std_code.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        std_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_codeActionPerformed(evt);
            }
        });
        getContentPane().add(std_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 187, -1));

        std_address.setColumns(20);
        std_address.setRows(5);
        jScrollPane1.setViewportView(std_address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 187, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("عنوان الطالب");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 330, 140, 86));

        std_religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_religionActionPerformed(evt);
            }
        });
        getContentPane().add(std_religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 187, -1));

        jButton1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton1.setText("اولياء الامور");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 145, -1));

        jButton2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton2.setText("اغلاق");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 187, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/images/contact.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 850, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void std_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_genderActionPerformed

    private void std_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_codeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.before_frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void std_religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_religionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Std_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea std_address;
    private com.toedter.calendar.JDateChooser std_brith_date;
    private javax.swing.JTextField std_code;
    private javax.swing.JComboBox<String> std_gender;
    private javax.swing.JTextField std_nat_id;
    private javax.swing.JTextField std_phone;
    private javax.swing.JComboBox<String> std_religion;
    // End of variables declaration//GEN-END:variables
}
